### ISSUE TITLE
 Information for improvement

### ISSUE THREAD

**Issue by dckiller51** [K-4U/custom_components#1]
Congratulations for this integration. Maybe you will find interesting information here.

https://github.com/mmakaay/esphome-xiaomi_bslamp2/tree/a5850e2bb212281362e6e997e33035546dc52aa0

Brightness invert does not work

```
  on_left:
    then:
      - light.dim_relative:
          id: light1
          relative_brightness: -5%
```
